name: KOTHPlugin
version: ${version}
main: com.techmc.koth.KOTHPlugin
api-version: "1.21"
author: techmc
description: King of the Hill minigame

commands:
  koth:
    description: KOTH commands
    usage: /koth <start|stop|setzone>
    permission: koth.admin
    permission-message: You don't have permission to use this command.

permissions:
  koth.admin:
    description: Allows using /koth admin commands
    default: op
